services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    container_name: immich_server
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ${DOCKER_VOLUMES_PATH}/immich/library:/data
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - redis
      - database
    expose:
      - 2283
    networks:
      - immich-internal
      - pangolin
    healthcheck:
      disable: false

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-openvino
    container_name: immich_machine_learning
    restart: unless-stopped
    user: ${PUID}:${PGID}
    devices:
      - /dev/dri:/dev/dri
    extends:
      file: ${DOCKER_VOLUMES_PATH}/immich/hwaccel.ml.yml
      service: openvino
    volumes:
      - ${DOCKER_VOLUMES_PATH}/immich/model:/cache
    healthcheck:
      disable: false

  redis:
    image: docker.io/valkey/valkey:8-bookworm@sha256:fea8b3e67b15729d4bb70589eb03367bab9ad1ee89c876f54327fc7c6e618571
    container_name: immich_redis
    restart: unless-stopped
    user: ${PUID}:${PGID}
    networks:
      - immich-internal
    healthcheck:
      test: redis-cli ping || exit 1

  database:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:41eacbe83eca995561fe43814fd4891e16e39632806253848efaf04d3c8a8b84
    container_name: immich_postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: --data-checksums
      # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
      DB_STORAGE_TYPE: 'HDD'
    user: ${PUID}:${PGID}
    volumes:
      - ${DOCKER_VOLUMES_PATH}/immich/postgres:/var/lib/postgresql/data
    shm_size: 128mb
    networks:
      - immich-internal

networks:
  immich-internal:
    name: immich_network
    driver: bridge
  pangolin:
    external: true
