services:
  wizarr:
    image: ghcr.io/wizarrrr/wizarr
    container_name: wizarr
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      DISABLE_BUILTIN_AUTH: ${DISABLE_BUILTIN_AUTH}
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${DOCKER_VOLUMES_PATH}/wizarr:/data
    expose:
      - 5690
    networks:
      - pangolin
networks:
  pangolin:
    external: true